### ISSUE TITLE
Dokumentace

### ISSUE THREAD

**Issue by patrickkusebauch** [nexendrie/EventCalendar#1]
Ahoj, super komponenta, dá se roběhnout super rychle a hezky podle toho quickstartu.

Nicméně pak se vůbec nemám od čeho odpíchnout a co pak dál s tím. Je k tomu nějaká další dokumentace? Nebo alespoň nějaké úryvky z kódu?

**Comment by konecnyjakub** [comment]
Ahoj. O jiné dokumentaci (jinde než tady) k téhle komponentě nevím. Ale SimpleCalendar používám v [jedné aplikaci](https://github.com/nexendrie/nexendrie), takže k němu jsou nějaké ukázky. [Presenter](https://github.com/nexendrie/nexendrie/blob/1.0.0-beta8/app/Presenters/FrontModule/ChroniclePresenter.php#L40-L56) [Model](https://github.com/nexendrie/nexendrie/blob/1.0.0-beta8/app/Model/Events.php#L114-L142)
Ke Google kalendáři zatím nic není.
Snad to aspoň trochu pomůže, než bude podrobnější dokumentace.

**Comment by patrickkusebauch** [comment]
Super, lepší než drátem do oka, díky moc. :)

**Comment by konecnyjakub** [comment]
Ahoj. Vývoj téhle komponenty se přesouvá na GitLab, tady na GitHubu se bude všechno zavírat. Tahle issue pokračuje na https://gitlab.com/nexendrie/EventCalendar/-/issues/1.
